--  This script represents the stored procedure used for replicating the
--  superuser authentication token from UFS_CRDB_UAT.OAUTH_ACCESS_TOKEN to UFS_SMART_SUITE.OAUTH_ACCESS_TOKEN.
--  This procedure is callable from the system and accepts a single string parameter representing the username
--  of the superuser.

CREATE OR REPLACE PROCEDURE UFS_CRDB_UAT."REPLICATE_AUTH_TOKEN"(
	USERNAME IN VARCHAR2
)
AS
NUM NUMBER;
TOKEN_ID_ VARCHAR2(100);
REFRESH_TOKEN_ VARCHAR(100);
AUTHENTICATION_ BLOB;
TOKEN_ BLOB;
BEGIN
BEGIN
SELECT COUNT(*) INTO NUM FROM UFS_SMART_SUITE.OAUTH_ACCESS_TOKEN WHERE USER_NAME =USERNAME;
END;

    IF NUM > 0 THEN
        SELECT TOKEN_ID ,REFRESH_TOKEN ,TOKEN ,AUTHENTICATION  INTO TOKEN_ID_,REFRESH_TOKEN_,TOKEN_,AUTHENTICATION_
        FROM UFS_CRDB_UAT.OAUTH_ACCESS_TOKEN oat WHERE USER_NAME =USERNAME;

    UPDATE UFS_SMART_SUITE.OAUTH_ACCESS_TOKEN SET
        TOKEN_ID = TOKEN_ID_ ,
        REFRESH_TOKEN = REFRESH_TOKEN_,
        TOKEN  = TOKEN_,
        AUTHENTICATION = AUTHENTICATION_
    WHERE USER_NAME =USERNAME;
    ELSE
        INSERT INTO UFS_SMART_SUITE.OAUTH_ACCESS_TOKEN SELECT * FROM OAUTH_ACCESS_TOKEN WHERE USER_NAME = USERNAME;
    END IF;
END;
